# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='photo',
            field=models.ImageField(default='/photos/dial.jpg', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='unite',
            field=models.CharField(default='', max_length=30),
        ),
    ]
