# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20160511_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='photo',
            field=models.ImageField(default='/media/photos/dial.jpg', upload_to='photos/'),
        ),
    ]
