# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenges', '0008_auto_20160516_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
