# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_challenge_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='team',
        ),
    ]
